debug: true

# Logger Config
logging:
  level:
    com.example.demo: debug

server:
  port: 9090

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    url: jdbc:mysql://119.23.67.69:3306/sys?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: gsjt654321,.

    druid:
      # 数据源配置
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20


mybatis-plus:
  check-config-location: false
  # MyBatis 配置文件位置，如果您有单独的 MyBatis 配置，请将其路径配置到 configLocation 中，具体配置参考官方文档 http://www.mybatis.org/mybatis-3/zh/configuration.html
#  config-location: classpath:mybatis/mybatis-config.xml
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置
#  mapper-locations: classpath*:**/*Mapper.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）。
  # type-aliases-package: com.baomidou.mybatisplus.samples.quickstart.model
  # type-aliases-super-type: java.lang.Object
  # type-handlers-package: com.baomidou.mybatisplus.samples.quickstart.handler
  executor-type: simple